const STEPS=[
  {id:"vocabulary",title:"Key Vocabulary"},
  {id:"language_takeaway",title:"Language Takeaway"},
  {id:"putting_it_together",title:"Putting It Together"},
  {id:"fluency_builder",title:"Fluency Builder"},
  {id:"audio_review",title:"Audio Review"}
];
let curLesson,curStep=0,audio,curUtterance=null;
function showHome(){const g=document.getElementById("lesson-grid");g.innerHTML="";for(const ls of LESSONS){const c=document.createElement("div");c.className="lesson-card";const vc=(ls.vocabulary||[]).length,lc=(ls.language_takeaway||[]).length;c.innerHTML='<div class="lesson-card-content"><div class="lesson-card-title">'+ls.title+'</div><div class="lesson-card-subtitle">'+vc+' vocab '+lc+' exprs</div></div><div class="lesson-card-arrow">\u2192</div>';c.onclick=()=>openLesson(ls);g.appendChild(c);}document.querySelectorAll(".page").forEach(p=>p.classList.remove("active"));document.getElementById("page-home").classList.add("active");}
function openLesson(ls){curLesson=ls;curStep=0;document.querySelectorAll(".page").forEach(p=>p.classList.remove("active"));document.getElementById("page-lesson").classList.add("active");document.getElementById("lesson-title").textContent=ls.title;setupAudio(ls);renderStep(0);}
function setupAudio(ls){audio=document.getElementById("audio-player");audio.src=ls.audio;audio.preload="auto";const pb=document.getElementById("play-btn"),pr=document.getElementById("progress-bar"),cu=document.getElementById("current-time"),to=document.getElementById("total-time");pb.onclick=()=>{if(audio.paused){audio.play().catch(()=>{});pb.innerHTML="\u25b6\u25b6";}else{audio.pause();pb.innerHTML="\u25b6";}};audio.onloadedmetadata=()=>{to.textContent=fmt(audio.duration);pr.max=Math.floor(audio.duration*10)/10;};audio.ontimeupdate=()=>{pr.value=audio.currentTime;cu.textContent=fmt(audio.currentTime);};audio.onended=()=>{pb.innerHTML="\u25b6";};pr.oninput=()=>{audio.currentTime=parseFloat(pr.value);};document.querySelectorAll(".spd").forEach(b=>{b.onclick=()=>{document.querySelectorAll(".spd").forEach(x=>x.classList.remove("act"));b.classList.add("act");audio.playbackRate=parseFloat(b.dataset.s);};});}
function renderStep(idx){curStep=idx;const step=STEPS[idx];document.getElementById("cur-step").textContent=idx+1;document.getElementById("step-title").textContent=step.title;document.querySelectorAll(".dot").forEach((d,i)=>d.classList.toggle("act",i===idx));document.getElementById("prev-step").style.visibility=idx===0?"hidden":"visible";document.getElementById("next-step").style.visibility=idx===STEPS.length-1?"hidden":"visible";const area=document.getElementById("content");switch(step.id){case"vocabulary":renderVocab(area);break;case"language_takeaway":renderLT(area);break;case"putting_it_together":renderPIT(area);break;case"fluency_builder":renderFB(area);break;case"audio_review":renderAR(area);break;}}
function esc(s){return String(s||"").replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;").replace(/"/g,"&quot;").replace(/\n/g,"<br>");}
function spk(t){
  if(!t)return;
  console.log("SPK:",t);
  window.speechSynthesis.cancel();
  curUtterance=new SpeechSynthesisUtterance(t);
  curUtterance.lang="en-US";
  curUtterance.rate=0.9;
  window.speechSynthesis.speak(curUtterance);
}
function refreshSpk(){document.querySelectorAll(".spk").forEach(function(b){b.onclick=null;b.removeAttribute("onclick");b.addEventListener("click",function(e){e.stopPropagation();var t=this.getAttribute("data-t")||this.textContent.replace(/[^\w\s\']/g,"").trim();spk(t);});});}
function renderVocab(area){const a=curLesson.vocabulary||[];if(!a.length){area.innerHTML='<div class="empty">No vocabulary.</div>';return;}let h="";for(const v of a){h+='<div class="card"><div class="card-title">'+esc(v.word)+'<button class="spk" data-t="'+esc(v.word)+'" onclick="spk(this.dataset.t)">&#128266;</button></div>';if(v.meaning)h+='<div class="vocab-meaning">'+esc(v.meaning)+'</div>';h+='</div>';}area.innerHTML=h;refreshSpk();}
function renderLT(area){const a=curLesson.language_takeaway||[];if(!a.length){area.innerHTML='<div class="empty">No content.</div>';return;}let h="";for(const e of a){h+='<div class="card lt-card"><div class="card-title">'+esc(e.expression)+'<button class="spk" data-t="'+esc(e.expression)+'" onclick="spk(this.dataset.t)">&#128266;</button></div>';if(e.explanation)h+='<div class="card-explanation">'+esc(e.explanation)+'<button class="spk" data-t="'+esc(e.explanation)+'" onclick="spk(this.dataset.t)">&#128266;</button></div>';if(e.example_1)h+='<div class="card-example"><span class="card-example-label">Example 1</span>'+esc(e.example_1)+'<button class="spk" data-t="'+esc(e.example_1)+'" onclick="spk(this.dataset.t)">&#128266;</button></div>';if(e.example_2)h+='<div class="card-example"><span class="card-example-label">Example 2</span>'+esc(e.example_2)+'<button class="spk" data-t="'+esc(e.example_2)+'" onclick="spk(this.dataset.t)">&#128266;</button></div>';h+='</div>';}area.innerHTML=h;refreshSpk();}
function renderPIT(area){const a=curLesson.putting_it_together||[];if(!a.length){area.innerHTML='<div class="empty">No content.</div>';return;}let h="";for(const e of a){h+='<div class="card pit-card"><div class="card-title">'+esc(e.expression)+'<button class="spk" data-t="'+esc(e.expression)+'" onclick="spk(this.dataset.t)">&#128266;</button></div>';if(e.example_1)h+='<div class="card-example"><span class="card-example-label">Example 1</span>'+esc(e.example_1)+'<button class="spk" data-t="'+esc(e.example_1)+'" onclick="spk(this.dataset.t)">&#128266;</button></div>';if(e.example_2)h+='<div class="card-example"><span class="card-example-label">Example 2</span>'+esc(e.example_2)+'<button class="spk" data-t="'+esc(e.example_2)+'" onclick="spk(this.dataset.t)">&#128266;</button></div>';h+='</div>';}area.innerHTML=h;refreshSpk();}
function renderFB(area){const a=curLesson.fluency_builder||[];if(!a.length){area.innerHTML='<div class="empty">No content.</div>';return;}let h="";for(const f of a){h+='<div class="card fb-card"><div class="card-title">Fluency Builder</div>';if(f.original||f.native){h+='<div class="fl-row">';if(f.original)h+='<span class="fl-original">'+esc(f.original)+'<button class="spk" data-t="'+esc(f.original)+'" onclick="spk(this.dataset.t)">&#128266;</button></span>';if(f.original&&f.native)h+='<span class="fl-arrow">\u2192</span>';if(f.native)h+='<span class="fl-native">'+esc(f.native)+'<button class="spk" data-t="'+esc(f.native)+'" onclick="spk(this.dataset.t)">&#128266;</button></span>';h+='</div>';}if(f.explanation)h+='<div class="card-explanation">'+esc(f.explanation)+'<button class="spk" data-t="'+esc(f.explanation)+'" onclick="spk(this.dataset.t)">&#128266;</button></div>';h+='</div>';}area.innerHTML=h;refreshSpk();}
function renderAR(area){const a=curLesson.audio_review||[];if(!a.length){area.innerHTML='<div class="empty">No review items.</div>';return;}let h='<p style="text-align:center;font-size:13px;color:#B8B0A3;margin-bottom:14px">Match the meaning</p>';for(let i=0;i<a.length;i++){const r=a[i];const ee=esc(r.expression).replace(/'/g,"\\'");h+='<div class="review-item"><div class="review-question">'+esc(r.meaning)+'</div><button class="review-btn" onclick="showAns(\''+ee+'\',this)">Show Answer</button><div class="review-answer" style="display:none"></div></div>';}area.innerHTML=h;refreshSpk();}
function showAns(ans,btn){const item=btn.parentElement;const answer=item.querySelector(".review-answer");answer.innerHTML=ans;const w=answer.style.display==="none";answer.style.display=w?"block":"none";btn.textContent=w?"Hide":"Show Answer";}
function fmt(s){if(!s||isNaN(s))return"0:00";const m=Math.floor(s/60),sc=Math.floor(s%60);return m+":"+(sc<10?"0":"")+sc;}
document.getElementById("back-home").onclick=showHome;
document.getElementById("prev-step").onclick=()=>{if(curStep>0)renderStep(curStep-1);};
document.getElementById("next-step").onclick=()=>{if(curStep<STEPS.length-1)renderStep(curStep+1);};
document.querySelectorAll(".dot").forEach(d=>d.onclick=()=>renderStep(parseInt(d.dataset.i)));
document.onkeydown=e=>{if(e.key==="ArrowLeft"&&curStep>0)renderStep(curStep-1);if(e.key==="ArrowRight"&&curStep<STEPS.length-1)renderStep(curStep+1);if(e.key===" "&&document.getElementById("page-lesson").classList.contains("active")){e.preventDefault();document.getElementById("play-btn").click();}};
// Speaker button event delegation
document.addEventListener("DOMContentLoaded",function(){document.body.addEventListener("click",function(e){var b=e.target.closest(".spk");if(b){e.preventDefault();var t=b.getAttribute("data-t")||b.textContent.replace(/[^\w\s\']/g,"").trim();console.log("speak:",t);spk(t);}});});
document.addEventListener("DOMContentLoaded",showHome);
